### ISSUE TITLE
Problem with the PUT request

### ISSUE THREAD

**Issue by ActiveByte** [combell/combell-api#1]
Hey there, what am i doing wrong? i'm trying to update a specific dns record

Code: 
`<?php
// SETTINGS
$domain = 'activebyte.be';
$recordtoupdate = "www";
// END OF SETTINGS

require 'vendor/autoload.php';

$client = new \Combell\Client(
    [
        'debug' => false,
        'base_uri' => 'https://api.combell.com',
        'combell_api_key' => 'apikey',
        'combell_api_secret' => 'apisecret'
    ]
);

// Update record
$response2 = $client->put('/v2/dns/activebyte.be/records/1-4779913029', [
    'form_params' => [
        'content' => '60.180.75.132',
    ],
    'timeout' => 5
]);

var_dump(
    json_decode($response2->getBody()->getContents())
);`

Output:

`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: 'PUT https://api.combell.com/v2/dns/activebyte.be/records/1-4779913029' resulted in a '415 Unsupported Media Type' response in D:\XAMPP\htdocs\combell\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 D:\XAMPP\htdocs\combell\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 D:\XAMPP\htdocs\combell\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 D:\XAMPP\htdocs\combell\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 D:\XAMPP\htdocs\combell\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 D:\XAMPP\htdocs\combell\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Promise\T in D:\XAMPP\htdocs\combell\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113`

**Comment by coudenysj** [comment]
Hi @ActiveByte,

As this isn't really a problem with the client PHP API wrapper, I suggest you contact Combell support directly to get this issue resolved.

Contact information is available at https://www.combell.com/nl/support.
